### ISSUE TITLE
Faces TAB Shows ERROR

### ISSUE THREAD

**Issue by MYLE-01** [UksusoFF/webtrees-faces#75]
Call to a member function mediaFiles() on null …/modules_v4/faces/resources/views/tab.phtml:4
#0 …/app/View.php(183): include()
#1 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#2 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#3 …/modules_v4/faces/src/Modules/FacesModule.php(217): view()
#4 …/app/Module/ModuleTabTrait.php(143): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->getTabContent()
#5 …/app/Http/RequestHandlers/ModuleAction.php(85): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->getTabAction()
#6 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle()
#7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#8 …/modules_v4/faces/src/Modules/FacesModule.php(94): Middleland\Dispatcher->handle()
#9 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process()
#10 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle()
#11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#12 …/app/Module/CheckForNewVersion.php(122): Middleland\Dispatcher->handle()
#13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#14 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#17 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#18 …/app/Http/Middleware/Router.php(161): Fisharebest\Webtrees\Webtrees::dispatch()
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#20 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#22 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#24 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#26 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle()
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#28 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#29 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#30 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#32 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#34 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#36 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#38 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#40 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#42 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#44 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle()
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#46 …/app/Http/Middleware/BadBotBlocker.php(282): Middleland\Dispatcher->handle()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#48 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#50 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#52 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#53 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#55 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#57 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle()
#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#59 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#60 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#61 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#62 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#63 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#64 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#65 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#66 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#67 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#68 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#69 {main}

Think It to do with Deleted Photos

If i go into the faces Module
![image](https://user-images.githubusercontent.com/4362345/217527556-94ba808d-3713-470c-8597-f32c4ede07d5.png)

it wont delete when i try to delete it 

got a work around

**Comment by MYLE-01** [comment]
I FTP a new file called "74aed983d8a32916592245f79f664e28096134c6.jpg" think it was missing but the file is there
must be something wrong in the database 

I know I delete some Images thinking thats was where the problem is

thats my thoughts

**Comment by MYLE-01** [comment]
FIX IT 

in the faces modules page in the Missed menu click on the remove DONE

thanks
